linkLevelMin: 1
linkLevelMax: 3
memSavingMethod: 0

short: Pali original and Latin translation

description: >-
  <p>Search interface for <a id="corpus2link" href="#"></a>.</p>
  <p>This search interface is by:</p>
  <ul>
      <li><a id="author2link" href="#"></a> («author2.role»)
      <li><a id="author1link" href="#"></a> («author1.role»)
  </ul>

defaultSettings:
  autoexec: true
  nodeseq: true
  exporthl: true
  exportsr: true
  multihl: true
  simple: false

defaultFlags:
  i: false
  m: true
  s: false

keyboard:
  'ā': '-a'
  'â': '^a'
  'ḍ': '.d'
  'ê': '^e'
  'ḥ': '.h'
  'ī': '-i'
  'î': '^i'
  'ḷ': '.l'
  'ṃ': '.m'
  'ṅ': ':n'
  'ṇ': '.n'
  'ñ': '~n'
  'ȏ': '^o'
  'ṭ': '.t'
  'ū': '-u'

layerSettings:
  word:
    description: words (Pali and Latin separately)
    layers:
      pali:
        beforeFeature: palipre
        afterFeature: palipost
        default: ""
        description: Pali original
        feature: pali
        pos: null
        visible: false
      latin:
        beforeFeature: latinpre
        afterFeature: latinpost
        default: ""
        description: Latin translation
        feature: latin
        pos: null
        visible: false
  stanza:
    afterDefault: "\n"
    description: stanzas (Pali and Latin linked)
    focus: true
    layers:
      number:
        default: ¿
        description: number of a stanza
        feature: n
        pos: null
        visible: true
      pali:
        default: ""
        description: Pali original
        descend: word
        beforeFeature: palipre
        afterFeature: palipost
        feature: pali
        pos: null
        visible: true
      latin:
        default: ""
        description: Latin translation
        descend: word
        beforeFeature: latinpre
        afterFeature: latinpost
        feature: latin
        pos: null
        visible: true
  vagga:
    afterDefault: "\n"
    description: Vaggas.
    layers:
      number:
        default: ¿
        description: number of a vagga
        feature: n
        pos: null
        visible: true
